version: '3.8'

services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webdb
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./web
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: webdb
      DB_USER: webuser
      DB_PASS: webpass
    ports:
      - "80:80"

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
